config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, controllers: {
   registrations: "users/registrations",
   omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :blogs, only: [:index, :new, :create, :edit, :update, :destroy] do
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root 'blogs#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
    validates :title, presence: true
    belongs_to :user
    default_scope -> { order(updated_at: :desc) }

    mount_uploader :picture, PictureUploader 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable

  mount_uploader :avatar, AvatarUploader

  has_many :blogs

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(email: auth.info.email)

    unless user
      user = User.new(
        name: auth.extra.raw_info.name,
        provider: auth.provider,
        uid: auth.uid,
        email: auth.info.email ||="#{auth.uid}-#{auth.provider}@example.com",
        image_url: auth.info.image,
        password: Devise.friendly_token[0,20]
      )
     user.skip_confirmation!
     user.save(validate: false)
    end
    user
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
        name: auth.info.nickname,
        image_url: auth.info.image,
        provider: auth.provider,
        uid: auth.uid,
        email: auth.info.email ||="#{auth.uid}-#{auth.provider}@example.com",
        password: Devise.friendly_token[0,20]
      )
     user.skip_confirmation!
     user.save
    end
    user
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_with_password(params, *options)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_actionで下で定義したメソッドを実行
  before_action :configure_permitted_parameters, if: :devise_controller?

  #変数PERMISSIBLE_ATTRIBUTESに配列[:name]を代入
  PERMISSIBLE_ATTRIBUTES = %i(name avatar avatar_cache)

  protected

    #deviseのストロングパラメーターにカラム追加するメソッドを定義
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
      devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:edit, :update, :destroy]
  #before_action :authenticate_user!

  def index
    @blogs = Blog.all
  end

  def new
      @blog = Blog.new
  end

  def create
    @blog = Blog.new(blogs_params)
    @blog.user_id = current_user.id
    if @blog.save
     redirect_to blogs_path, success: "投稿しました！"
    else
     render 'new'
    end
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blogs_params)
     redirect_to blogs_path, notice: "投稿を更新しました！"
    else
     render 'edit'
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, danger: "投稿を削除しました！"
  end

  private
   def blogs_params
     params.require(:blog).permit(:title, :content, :picture, :picture_cache)
   end

   def set_blog
     @blog = Blog.find(params[:id])
   end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"],current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"],current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except["extra"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def profile_img(user,page)
    return image_tag(user.avatar, alt: user.name, class:'img-circle') if user.avatar?

    unless user.provider.blank?
      img_url = user.image_url
    else
      img_url = 'no_image.png'
    end

    if page == 'blogs'
     image_tag(img_url, alt: user.name, class:'img-circle')
    else
     image_tag(img_url, alt: user.name)
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
   if action_name == 'new'
     blogs_path
   elsif action_name == 'edit'
     blog_path
   end
  end
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/blogs/_form.html.erb
<p id="notice"><%= notice %></p>

<%= form_for(@blog, url: choose_new_or_edit) do |f| %>
 <% if @blog.errors.any? %>
  <div id="error_explanation">
   <h2><%= @blog.errors.count %>件のエラーがあります。</h2>

   <ul>
   <% @blog.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
   <% end %>
   </ul>
  </div>
 <% end %>

  <%= f.label :タイトル %>
  <%= f.text_field :title, class: 'form-control' %>
  <br>
  <%= f.label :内容 %>
  <%= f.text_field :content, class: 'form-control' %>
  <br>
  <%= image_tag @blog.picture if @blog.picture %>
  <%= f.file_field :picture %>
  <%= f.hidden_field :picture_cache %>
  <br>

  <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>

<% end %>

<%= link_to "ブログ一覧に戻る", blogs_path %>

app/views/blogs/edit.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <h2>編集</h2>
    <%= render 'form' %>
 </div>
</div>

app/views/blogs/index.html.erb
<div class="container">
 <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">

   <% if user_signed_in? %>
     <%= link_to "投稿", new_blog_path, class: 'btn btn-default' %>
   <% end %>

   <% @blogs.each do |blog| %>
   <div class="row" id="row1">
    <div class="col">
      <h4><strong><%= blog.title %></strong></h4>
      <p class="img"><%= image_tag blog.picture if blog.picture %></p>
      <p><%= blog.content %></p>
    </div>
   </div>
   <div class="row" id="row2">
     <div class="col" id="col1">
       <% if user_signed_in? && blog.user_id == current_user.id %>
        <%= link_to "編集", edit_blog_path(blog.id), class: 'btn btn-sml btn-success' %>
        <%= link_to "削除", blog_path(blog.id), method: :delete, data: {confirm: '本当に削除していいですか？'}, class: 'btn btn-sml btn-danger' %>
       <% end %>
     </div>
    <div class="col" id="col2">
      <p><%= blog.user.name %></p>
      <p id="tw_date">
       作成日:<%= blog.created_at.to_s(:datetime) %><br>
       更新日:<%= blog.updated_at.to_s(:datetime) %></p>
    </div>
   </div>
   <% end %>
 </div>
</div>

app/views/blogs/new.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <h2>作成</h2>
    <%= render 'form' %>
 </div>
</div>

app/views/layouts/application.html のコピー.erb
<!DOCTYPE html>
<html>
<head>
  <title>instagram-clone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <header>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav">
          <li><%= link_to "", root_path, class: "glyphicon glyphicon-home" %></li>
        </ul>

        <button type="button" class="btn btn-default">
          <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        </button>

        <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "", blogs_path, class: "glyphicon glyphicon-time" %></li>
                <li><%= link_to "", blogs_path, class: "glyphicon glyphicon-heart-empty" %></li>
              <% if user_signed_in? %>
                <li><%= link_to "", edit_user_registration_path, class: "glyphicon glyphicon-user" %></li>
                <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "ログイン", new_user_session_path %></li>
                <li><%= link_to "サインアップ", new_user_registration_path %></li>
              <% end %>
        </ul>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  </header>

  <% flash.each do |key, value| %>
    <% key = "info" if key == "notice" %>
    <% key = "danger"  if key == "alert" %>
    <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>

  <%= yield %>

  <footer>
    <p>運営会社DIVE INTO CODE株式会社</p>
    <p>© 2015-2016 Copyright DIVE INTO CODE Corp.</p>
  </footer>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>instagram-clone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <header>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">

     　<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
    　   <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>

        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "", root_path, class: "glyphicon glyphicon-home" %></li>
          <li><%= link_to "¿Instagram?", root_path, id: "navhome" %></li>
        </ul>

      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "", blogs_path, class: "glyphicon glyphicon-time" %></li>
            <li><%= link_to "", blogs_path, class: "glyphicon glyphicon-heart-empty" %></li>
          <% if user_signed_in? %>
            <li><%= link_to "", edit_user_registration_path, class: "glyphicon glyphicon-user" %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "ログイン", new_user_session_path %></li>
            <li><%= link_to "サインアップ", new_user_registration_path %></li>
          <% end %>
        </ul>

        <form class="navbar-form navbar-right" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="検索キーワード">
          </div>
          <button type="submit" class="btn btn-default">検索</button>
        </form>
      </div>

    </div><!-- /.container-fluid -->
  </nav>
  </header>

  <% flash.each do |key, value| %>
    <% key = "info" if key == "notice" %>
    <% key = "danger"  if key == "alert" %>
    <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>

  <%= yield %>

  <footer>
    <p>運営会社DIVE INTO CODE株式会社</p>
    <p>© 2015-2016 Copyright DIVE INTO CODE Corp.</p>
  </footer>

</body>
</html>